#!/bin/bash

red='\e[31m'
green='\e[32m'
yellow='\e[33m'
normal='\e[0m'

function heading {
    local msg=" $1 "
    # shellcheck disable=SC2155
    local max=$(tput cols)
    # shellcheck disable=SC2155
    local rule="$(printf '%.0s=' $(seq "$max"))"

    local center=${#msg}
    local left=$(((max - center) / 2))
    [ $left -lt 0 ] && left=0
    local right=$((left + center))

    echo -e "$yellow${rule::left}$msg${rule:right}$normal"
}

function error_handler {
    echo -e "${red}An error occured during the installation process!${normal}"
    echo -e "$red(Line $1) Command: $2$normal"
    read -r -p 'For more details, see the error log above. Press Enter to exit...' _
    exit 1
}

if [ "$EUID" -ne 0 ]; then
    sudo "$(realpath "$0")" || exit 1
else
    read -r -p 'In order to install the most recent TeX Live version, 
        this script will erase all previous iterations. Press enter to
        procced, otherwise Ctrl-C...' _

    trap 'error_handler $LINENO $BASH_COMMAND' ERR

    heading 'Deleting older versions'
    find /usr/local/texlive -maxdepth 1 -type d -name '[0-9]*' -exec rm -rf {} +
    find "/home/$SUDO_USER" -maxdepth 1 -type d -name '.texlive[0-9]*' -exec rm -rf {} +
    echo -e "${green}Done!${normal}"

    heading 'Installing TeX Live'
    apt install -y perl-tk perl-doc wget
    # shellcheck disable=SC2164
    cd "$(mktemp -d)"
    wget 'http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz' -O install-tl-unx.tar.gz
    tar -xf install-tl-unx.tar.gz
    cat << 'EOF' > texlive.profile
selected_scheme scheme-full
instopt_adjustpath 0
instopt_adjustrepo 1
instopt_letter 0
instopt_portable 0
instopt_write18_restricted 1
tlpdbopt_autobackup 1
tlpdbopt_backupdir tlpkg/backups
tlpdbopt_create_formats 1
tlpdbopt_desktop_integration 1
tlpdbopt_file_assocs 1
tlpdbopt_generate_updmap 0
tlpdbopt_install_docfiles 1
tlpdbopt_install_srcfiles 1
tlpdbopt_post_code 1
tlpdbopt_sys_bin /usr/local/bin
tlpdbopt_sys_info /usr/local/share/info
tlpdbopt_sys_man /usr/local/share/man
tlpdbopt_w32_multi_user 1
EOF
    "$(find ./ -type f -name 'install-tl' | head -1)" --profile texlive.profile --no-interaction
    echo -e "${green}Done!${normal}"

    heading 'Creating symlink to the bin directory'
    mkdir -p /opt
    ln -sf "$(find /usr/local/texlive -maxdepth 1 -type d -name '[0-9]*')/bin/*-linux" /opt/texbin
    echo -e "${green}Done!${normal}"

    heading 'Installing fonts'
    cp "$(/opt/texbin/kpsewhich -var-value TEXMFSYSVAR)/fonts/conf/texlive-fontconfig.conf" /etc/fonts/conf.d/09-texlive.conf
    fc-cache -fsv
    echo -e "${green}Done!${normal}"

    heading 'Configuring the environment'
    # shellcheck disable=SC2016
    [ ! -f /etc/profile.d/texlive.sh ] && echo 'export PATH=/opt/texbin:${PATH}' > /etc/profile.d/texlive.sh
    alias mktexlsr > /dev/null 2>&1 || echo "alias mktexlsr='sudo /opt/texbin/mktexlsr'" >> "/home/$SUDO_USER/.bash_aliases"
    alias updmap-sys > /dev/null 2>&1 || echo "alias updmap-sys='sudo /opt/texbin/updmap-sys'" >> "/home/$SUDO_USER/.bash_aliases"
    alias fmtutil-sys > /dev/null 2>&1 || echo "alias fmtutil-sys='sudo /opt/texbin/fmtutil-sys'" >> "/home/$SUDO_USER/.bash_aliases"
    alias sutlmgr > /dev/null 2>&1 || echo "alias sutlmgr='sudo /opt/texbin/tlmgr -gui'" >> "/home/$SUDO_USER/.bash_aliases"
    echo -e "${green}Done!${normal}"

    heading 'Cleaning up'
    apt autopurge -y perl-doc
    echo -e "${green}Done!${normal}"

    clear
    echo -e "${green}Installation completed!${normal}"
    cat << 'EOF'
Note: run 'sutlmgr' to execute the TeX Live manager, useful to update 
the packages of the distribution. If it crashes on update, probably you 
need to update it by running 'sutlmgr update --self'. Other useful 
aliases: mktexlsr, updmap-sys, fmtutil-sys.
EOF
    read -r -p 'Press Enter to logout or Ctrl-C to do it later...' _
    loginctl terminate-user "$SUDO_USER"
fi
